routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix(LaravelLocalization::setLocale().'/admin')
    ->middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')
    ->group(function () {

        Route::group(['as' => 'admin.'], function() {

            Route::name('login')->get('login','Auth\LoginController@showLoginForm');
            Route::name('login.submit')->post('login', 'Auth\LoginController@login');
            Route::name('logout')->get('logout', 'Auth\LoginController@logout');

            Route::name('index')->get('', ['uses' => 'IndexController@index']);

            // applications
            Route::name('applications.index')->get('applications', ['uses' => 'IndexController@applications']);
            Route::name('applications.show')->get('applications/{participant}', ['uses' => 'IndexController@applicationsShow']);
            Route::name('applications.delete')->get('applications/{participant}/delete', ['uses' => 'IndexController@applicationsDelete']);

            // events
            Route::group(['as' => 'events.'], function() {
                Route::name('index')->get('/events', ['uses' => 'EventController@index']);
                Route::name('data')->get('/events/data', ['uses' => 'EventController@data']);
                Route::name('data.add')->post('/events/data/add', ['uses' => 'EventController@add']);
                Route::name('data.view')->get('/events/data/view/{id}', ['uses' => 'EventController@view']);
                Route::name('data.delete')->delete('/events/data/delete/{row}', ['uses' => 'EventController@delete']);
            });

            // Report
            Route::group(['as' => 'report.'], function() {
                Route::name('index')->get('/report', ['uses' => 'ReportController@index']);
                Route::name('ishtapp')->get('/report/ishtapp', ['uses' => 'ReportController@ishtapp']);
                Route::name('ishtapp.users')->get('/report/ishtapp/users', ['uses' => 'ReportController@ishtappUsers']);
                Route::name('ishtapp.companies')->get('/report/ishtapp/companies', ['uses' => 'ReportController@ishtappCompanies']);
                Route::name('ishtapp.opportunities')->get('/report/ishtapp/opportunities', ['uses' => 'ReportController@ishtappOpportunities']);
            });

            /*
             * ADMIN CONTROL
            */

            Route::resources([
                'roles' => 'RoleController',
                'permissions' => 'PermissionController',
                'topics' => 'TopicController',
                'exercises'=>'ExerciseController',
                'users' => 'UserController',
                'participants' => 'ParticipantController',
                'regions' => 'RegionController',
                'sdg' => 'SdgController',
                'teams' => 'TeamController',
                'materials' => 'MaterialController',
                'grades' => 'GradeController',
                'mail_messages' => 'MailMessageController',
            ]);

            // Participant Routes
            Route::name('participants.grade')->post('/participants/{participant}/grade', ['uses' => 'ParticipantController@grade']);

            // Team Routes
            Route::name('teams.delete_user')->get('teams/{team}/delete/{participant}', ['uses' => 'TeamController@delete_user']);
            Route::name('teams.particiantAdd')->post('teams/{team}/add/participant', ['uses' => 'TeamController@particiantAdd']);

            // Exercise Routes
            Route::name('exercise.participant.info')->post('exercise/{exercise}/participant/info', ['uses' => 'ExerciseController@participantInfo']);
            Route::name('exercise.team.info')->post('exercise/{exercise}/team/info', ['uses' => 'ExerciseController@teamInfo']);
            Route::name('exercise.participant.grade')->post('exercise/{exercise}/participant/grade', ['uses' => 'ExerciseController@participantGrade']);
            Route::name('exercise.team.grade')->post('exercise/{exercise}/team/grade', ['uses' => 'ExerciseController@teamGrade']);
            Route::name('exercise.create_')->get('exercise/{topic}/create', ['uses' => 'ExerciseController@create_']);

            // Materials Routes
            Route::name('material.create_')->get('material/{topic}/create', ['uses' => 'MaterialController@create_']);

            // Delete Routes
            Route::name('teams.delete')->get('teams/{team}/delete', ['uses' => 'TeamController@destroy']);
            Route::name('permissions.delete')->get('permissions/{permission}/delete', ['uses' => 'PermissionController@destroy']);
            Route::name('roles.delete')->get('roles/{role}/delete', ['uses' => 'RoleController@destroy']);
            Route::name('users.delete')->get('users/delete/{user}', ['uses' => 'UserController@destroy']);
            Route::name('participants.delete')->get('participants/delete/{participant}', ['uses' => 'ParticipantController@destroy']);
            Route::name('regions.delete')->get('regions/delete/{region}', ['uses' => 'RegionController@destroy']);
            Route::name('sdg.delete')->get('sdg/delete/{sdg}', ['uses' => 'SdgController@destroy']);
            Route::name('exercises.delete')->get('exercise/{exercise}/delete', ['uses' => 'ExerciseController@delete']);
            Route::name('topics.delete')->get('topic/{topic}/delete', ['uses' => 'TopicController@delete']);
            Route::name('materials.delete')->get('material/{material}/delete', ['uses' => 'MaterialController@delete']);
            Route::name('grades.delete')->get('grades/{grade}/delete', ['uses' => 'GradeController@delete']);
            Route::name('mail_messages.delete')->get('mail_messages/{mail_message}/delete', ['uses' => 'MailMessageController@delete']);

            // User [login, password] change
            Route::name('users.changeLogin')->put('users/changeLogin/{user}',  ['uses' => 'UserController@changeLogin']);
            Route::name('users.changePassword')->put('users/changePassword/{user}',  ['uses' => 'UserController@changePassword']);
            /*
             * LANDING PAGE CONTROL
            */
            Route::group(['as' => 'landing.'], function() {
                Route::resources([
                    'news' => 'NewsController',
                    'feedbacks' => 'FeedbackController',
                    'mentors' => 'MentorController'
                ]);

                Route::name('news.delete')->get('news/delete/{news}', ['uses' => 'NewsController@destroy']);
                Route::name('feedbacks.delete')->get('feedbacks/delete/{feedback}', ['uses' => 'FeedbackController@destroy']);
                Route::name('mentors.delete')->get('mentors/delete/{mentor}', ['uses' => 'MentorController@destroy']);
            });
        });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')->prefix(LaravelLocalization::setLocale())->group(function () {

    Route::name('web.index')->get('', 'IndexController@index');
    Route::name('web.news')->get('news', 'IndexController@news');
    Route::name('web.news.single')->get('news/single/{id}', 'IndexController@newsSingle');

    Route::name('participant.apply')->get('apply','IndexController@showApplyForm');
    Route::name('participant.apply.submit')->post('apply', 'IndexController@apply');

    Route::name('web.login')->get('login', 'IndexController@login');
    Route::name('web.login.submit')->post('login', 'IndexController@loginSubmit');

});

resources/views/admin/applications.blade.php
@extends('admin.default')

@section('title', $title)

@section('styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-6">
            <!--begin::Card title-->
            <div class="card-title">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                    <span class="svg-icon svg-icon-1 position-absolute ms-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <input type="text" id="search_handler" class="form-control w-250px ps-14" placeholder="Поиск" />
                </div>
                <!--end::Search-->
            </div>
            <!--end::Card title-->
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        <div class="card-body py-4 position-relative">
            <!--begin: Datatable-->
            <table id="dataTable" class="table align-middle table-row-dashed table-row-dashed fs-6 gy-5">
                <thead>
                <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                    <th class="w-30px">№</th>
                    <th>Ф.И.О.</th>
                    <th>Эл. адрес</th>
                    <th>Телефон</th>
                    <th>Пол</th>
                    <th>Населенный пункт</th>
                    <th>Дата подачи</th>
                    <th class="text-end min-w-100px">Действия</th>
                </tr>
                </thead>
                <tbody class="text-gray-600 fw-bold"></tbody>
            </table>
            <!--end: Datatable-->
        </div>
        <!--end::Card body-->
    </div>

@endsection

@section('scripts')
    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}"></script>

    <script>
        let table = $('#dataTable').DataTable({
            dom: 'tr'+
                '<"row"<"col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start"li><"col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end dataTables_pager"p>>',
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.applications.index') }}',
                data: function(d) {
                }
            },
            columns: [
                { data: 'id'},
                { data: 'full_name'},
                { data: 'email'},
                { data: 'phone'},
                { data: 'gender'},
                { data: 'region'},
                { data: 'created_at'},
                { data: 'actions', className: 'text-end'},
            ],
            order: [[ 6, "asc" ]],
            pageLength: 20,
            lengthMenu: ['20', '30', '40', '50', '100'],
            language: {
                "url": "{{asset('assets/js/russian.json')}}"
            },
        });

        // Search Datatable
        const filterSearch = $('#search_handler');

        filterSearch.keyup(function (e) {
            table.search(e.target.value).draw();
        });

    </script>
@endsection

resources/views/admin/default.blade.php
<!DOCTYPE html>

<html lang="en">
<!--begin::Head-->
<head><base href="">
    <title>@yield('title') | Админ-панель | UStart</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Favicons -->
    <link rel="icon" href="{{asset('favicon.ico')}}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!--begin::Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;500;600;700;900&display=swap" rel="stylesheet">
    <!--end::Fonts-->

    @yield('pre_styles')

    <!--begin::Global Stylesheets Bundle(used by all pages)-->
    <link href="{{asset('assets/plugins/global/plugins.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/css/style.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/css/app.css')}}" rel="stylesheet" type="text/css" />
    <!--end::Global Stylesheets Bundle-->

    <!--begin::Custom styles-->
    @yield('styles')
    @stack('styles')
    <!--end::Custom styles-->
</head>
<!--end::Head-->
<!--begin::Body-->
<body id="kt_body" class="header-extended header-fixed header-tablet-and-mobile-fixed">
<!--begin::Main-->
<!--begin::Root-->
<div class="d-flex flex-column flex-root">
    <!--begin::Page-->
    <div class="page d-flex flex-row flex-column-fluid">
        <!--begin::Wrapper-->
        <div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">

            @include('admin.partials.header')

            @yield('toolbar')

            <!--begin::Container-->
            <div id="kt_content_container" class="d-flex flex-column-fluid align-items-start container-xxl">
                <!--begin::Post-->
                <div class="content flex-row-fluid" id="kt_content">

                    @yield('content')

                </div>
                <!--end::Post-->
            </div>
            <!--end::Container-->
            @include('admin.partials.footer')

        </div>
        <!--end::Wrapper-->
    </div>
    <!--end::Page-->
</div>
<!--end::Root-->
<!--end::Main-->

<!--begin::Scrolltop-->
<div id="kt_scrolltop" class="scrolltop" data-kt-scrolltop="true">
    <!--begin::Svg Icon | path: icons/duotune/arrows/arr066.svg-->
    <span class="svg-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
            <rect opacity="0.5" x="13" y="6" width="13" height="2" rx="1" transform="rotate(90 13 6)" fill="black" />
            <path d="M12.5657 8.56569L16.75 12.75C17.1642 13.1642 17.8358 13.1642 18.25 12.75C18.6642 12.3358 18.6642 11.6642 18.25 11.25L12.7071 5.70711C12.3166 5.31658 11.6834 5.31658 11.2929 5.70711L5.75 11.25C5.33579 11.6642 5.33579 12.3358 5.75 12.75C6.16421 13.1642 6.83579 13.1642 7.25 12.75L11.4343 8.56569C11.7467 8.25327 12.2533 8.25327 12.5657 8.56569Z" fill="black" />
        </svg>
    </span>
    <!--end::Svg Icon-->
</div>
<!--end::Scrolltop-->

<!--begin::Javascript-->
<script>var hostUrl = "assets/";</script>
<!--begin::Global Javascript Bundle(used by all pages)-->
<script src="{{asset('assets/plugins/global/plugins.bundle.js')}}"></script>
<script src="{{asset('assets/js/scripts.bundle.js')}}"></script>
<!--end::Global Javascript Bundle-->
<script>
    $.ajaxSetup({
        headers: { 'X-CSRF-Token': $('meta[name=csrf-token]').attr('content') }
    });
</script>

@yield('scripts')
@stack('scripts')
</body>

<!--end::Body-->
</html>