routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix(LaravelLocalization::setLocale().'/admin')
    ->middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')
    ->group(function () {

        Route::group(['as' => 'admin.'], function() {

            Route::name('login')->get('login','Auth\LoginController@showLoginForm');
            Route::name('login.submit')->post('login', 'Auth\LoginController@login');
            Route::name('logout')->get('logout', 'Auth\LoginController@logout');

            Route::name('index')->get('', ['uses' => 'IndexController@index']);

            // applications
            Route::name('applications.index')->get('applications', ['uses' => 'IndexController@applications']);
            Route::name('applications.show')->get('applications/{participant}', ['uses' => 'IndexController@applicationsShow']);
            Route::name('applications.delete')->get('applications/{participant}/delete', ['uses' => 'IndexController@applicationsDelete']);

            // events
            Route::group(['as' => 'events.'], function() {
                Route::name('index')->get('/events', ['uses' => 'EventController@index']);
                Route::name('data')->get('/events/data', ['uses' => 'EventController@data']);
                Route::name('data.add')->post('/events/data/add', ['uses' => 'EventController@add']);
                Route::name('data.view')->get('/events/data/view/{id}', ['uses' => 'EventController@view']);
                Route::name('data.delete')->delete('/events/data/delete/{row}', ['uses' => 'EventController@delete']);
            });

            // Report
            Route::group(['as' => 'report.'], function() {
                Route::name('index')->get('/report', ['uses' => 'ReportController@index']);
                Route::name('ishtapp')->get('/report/ishtapp', ['uses' => 'ReportController@ishtapp']);
                Route::name('ishtapp.users')->get('/report/ishtapp/users', ['uses' => 'ReportController@ishtappUsers']);
                Route::name('ishtapp.companies')->get('/report/ishtapp/companies', ['uses' => 'ReportController@ishtappCompanies']);
                Route::name('ishtapp.opportunities')->get('/report/ishtapp/opportunities', ['uses' => 'ReportController@ishtappOpportunities']);
            });

            /*
             * ADMIN CONTROL
            */

            Route::resources([
                'roles' => 'RoleController',
                'permissions' => 'PermissionController',
                'topics' => 'TopicController',
                'exercises'=>'ExerciseController',
                'users' => 'UserController',
                'participants' => 'ParticipantController',
                'regions' => 'RegionController',
                'sdg' => 'SdgController',
                'teams' => 'TeamController',
                'materials' => 'MaterialController',
                'grades' => 'GradeController',
                'mail_messages' => 'MailMessageController',
            ]);

            // Participant Routes
            Route::name('participants.grade')->post('/participants/{participant}/grade', ['uses' => 'ParticipantController@grade']);

            // Team Routes
            Route::name('teams.delete_user')->get('teams/{team}/delete/{participant}', ['uses' => 'TeamController@delete_user']);
            Route::name('teams.particiantAdd')->post('teams/{team}/add/participant', ['uses' => 'TeamController@particiantAdd']);

            // Exercise Routes
            Route::name('exercise.participant.info')->post('exercise/{exercise}/participant/info', ['uses' => 'ExerciseController@participantInfo']);
            Route::name('exercise.team.info')->post('exercise/{exercise}/team/info', ['uses' => 'ExerciseController@teamInfo']);
            Route::name('exercise.participant.grade')->post('exercise/{exercise}/participant/grade', ['uses' => 'ExerciseController@participantGrade']);
            Route::name('exercise.team.grade')->post('exercise/{exercise}/team/grade', ['uses' => 'ExerciseController@teamGrade']);
            Route::name('exercise.create_')->get('exercise/{topic}/create', ['uses' => 'ExerciseController@create_']);

            // Materials Routes
            Route::name('material.create_')->get('material/{topic}/create', ['uses' => 'MaterialController@create_']);

            // Delete Routes
            Route::name('teams.delete')->get('teams/{team}/delete', ['uses' => 'TeamController@destroy']);
            Route::name('permissions.delete')->get('permissions/{permission}/delete', ['uses' => 'PermissionController@destroy']);
            Route::name('roles.delete')->get('roles/{role}/delete', ['uses' => 'RoleController@destroy']);
            Route::name('users.delete')->get('users/delete/{user}', ['uses' => 'UserController@destroy']);
            Route::name('participants.delete')->get('participants/delete/{participant}', ['uses' => 'ParticipantController@destroy']);
            Route::name('regions.delete')->get('regions/delete/{region}', ['uses' => 'RegionController@destroy']);
            Route::name('sdg.delete')->get('sdg/delete/{sdg}', ['uses' => 'SdgController@destroy']);
            Route::name('exercises.delete')->get('exercise/{exercise}/delete', ['uses' => 'ExerciseController@delete']);
            Route::name('topics.delete')->get('topic/{topic}/delete', ['uses' => 'TopicController@delete']);
            Route::name('materials.delete')->get('material/{material}/delete', ['uses' => 'MaterialController@delete']);
            Route::name('grades.delete')->get('grades/{grade}/delete', ['uses' => 'GradeController@delete']);
            Route::name('mail_messages.delete')->get('mail_messages/{mail_message}/delete', ['uses' => 'MailMessageController@delete']);

            // User [login, password] change
            Route::name('users.changeLogin')->put('users/changeLogin/{user}',  ['uses' => 'UserController@changeLogin']);
            Route::name('users.changePassword')->put('users/changePassword/{user}',  ['uses' => 'UserController@changePassword']);
            /*
             * LANDING PAGE CONTROL
            */
            Route::group(['as' => 'landing.'], function() {
                Route::resources([
                    'news' => 'NewsController',
                    'feedbacks' => 'FeedbackController',
                    'mentors' => 'MentorController'
                ]);

                Route::name('news.delete')->get('news/delete/{news}', ['uses' => 'NewsController@destroy']);
                Route::name('feedbacks.delete')->get('feedbacks/delete/{feedback}', ['uses' => 'FeedbackController@destroy']);
                Route::name('mentors.delete')->get('mentors/delete/{mentor}', ['uses' => 'MentorController@destroy']);
            });
        });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')->prefix(LaravelLocalization::setLocale())->group(function () {

    Route::name('web.index')->get('', 'IndexController@index');
    Route::name('web.news')->get('news', 'IndexController@news');
    Route::name('web.news.single')->get('news/single/{id}', 'IndexController@newsSingle');

    Route::name('participant.apply')->get('apply','IndexController@showApplyForm');
    Route::name('participant.apply.submit')->post('apply', 'IndexController@apply');

    Route::name('web.login')->get('login', 'IndexController@login');
    Route::name('web.login.submit')->post('login', 'IndexController@loginSubmit');

});

app/Models/Material.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Material extends Model
{
    use SearchableTrait;

    protected $table = 'materials';

    protected $guarded = ['id'];

    protected $searchable = [
        'columns' => [
            'materials.name' => 10
        ]
    ];

    public function topic(){
        return $this->belongsTo(Topic::class, 'topic_id');
    }

    public function getTopic(){
        $topic = Topic::findOrFail($this->topic_id);
        if ($topic){
            return $topic->name;
        }
        return null;
    }

    public function getVideo(){
        if (preg_match("#(?<=v=)[a-zA-Z0-9-]+(?=&)|(?<=v\/)[^&\n]+|(?<=v=)[^&\n]+|(?<=youtu.be/)[^&\n]+#", $this->videourl, $matches)){
            if ($matches[0])
                return $matches[0];
        };
        return null;
    }


}

app/Http/Controllers/Admin/MaterialController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Material;
use App\Models\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class MaterialController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:materials-index');
        $this->middleware('permission:materials-create', ['only' => ['create','store']]);
        $this->middleware('permission:materials-update', ['only' => ['edit','update']]);
        $this->middleware('permission:materials-delete', ['only' => ['destroy']]);
    }
    public function create(){
        $title = 'Форма создания материала';
        $row = new Material();
        $topics = Topic::pluck('name', 'id')->toArray();
        return view('admin.materials.create', compact('title', 'row', 'topics'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'description' => ['required'],
//            'link' => ['required'],
            'type' => ['required'],
            'topic_id' => ['required'],
        ], array(
            'name.required' => 'Поля является объзательным к заполнению',
            'description.required' => 'Поля является объзательным к заполнению',
            'type.required' => 'Поля является объзательным к заполнению',
            'topic_id.required' => 'Поля является объзательным к заполнению',
//            'link.required' => 'Поля является объзательным к заполнению',
        ));

        if ($validator->fails()) {
            return redirect()->route('admin.materials.create')
                ->withErrors($validator)
                ->withInput();
        }
        $data = $request->only('name', 'description', 'link', 'videourl', 'file', 'type', 'topic_id');
        $data['user_id'] = auth()->user()->id;
        $material = Material::create($data);
        if($request->hasFile('file')){
            $file = $request->file('file');

            $dir  = 'assets/materials/';
            if (!file_exists($dir)) {
                mkdir($dir, 0777, true);
            }
            $current = date('YmdHs');
            $filename = $material->id.'-'.Str::slug($material->name, '-').'-'.auth()->user()->id.'.'.$current.'-'.$file->getClientOriginalExtension();

            if($file->move(public_path($dir), $filename)){
                $material->file = $dir.$filename;
                $material->save();

                return redirect(route('admin.topics.index'));
            }
        }
        return redirect(route('admin.topics.index'));
    }

    public function show(Material $material){
        $title = 'Материал';
        $row = $material;
        return view('admin.materials.show', compact('title', 'row'));
    }

    public function edit(Material $material){
        $title = 'Форма редактирования материала';
        $row = $material;
        $topics = Topic::pluck('name', 'id')->toArray();
        return view('admin.materials.edit', compact('row', 'topics', 'title'));
    }

    public function update(Request $request, Material $material){
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'description' => ['required'],
            'type' => ['required'],
            'topic_id' => ['required'],
        ], array(
            'name.required' => 'Поля является объзательным к заполнению',
            'description.required' => 'Поля является объзательным к заполнению',
            'type.required' => 'Поля является объзательным к заполнению',
            'topic_id.required' => 'Поля является объзательным к заполнению',
        ));

        if ($validator->fails()) {
            return redirect()->route('admin.materials.edit', $material)
                ->withErrors($validator)
                ->withInput();
        }
        $data = $request->only('name', 'description', 'link', 'videourl', 'file', 'type', 'topic_id');
        $material->update($data);
        if($request->hasFile('file')){
            $file = $request->file('file');

            $dir  = 'assets/materials/';
            if (!file_exists($dir)) {
                mkdir($dir, 0777, true);
            }
            $current = date('YmdHs');
            $filename = $material->id.'-'.Str::slug($material->name, '-').'-'.auth()->user()->id.'.'.$current.'-'.$file->getClientOriginalExtension();

            if($file->move(public_path($dir), $filename)){
                $material->file = $dir.$filename;
                $material->save();

                redirect(route('admin.topics.index'));
            }
        }
        return redirect(route('admin.topics.index'));
    }

    public function delete(Material $material){
        $material->delete();
        return redirect(route('admin.topics.index'));
    }
}

app/Http/Controllers/Participant/MaterialController.php
<?php

namespace App\Http\Controllers\Participant;

use App\Models\Exercise;
use App\Models\Material;
use App\Models\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class MaterialController extends Controller
{
    public function show(Material $material){
        $title = 'Материал';
        $row = $material;
        $materials = Material::where('topic_id', $material->topic_id)->where('id', '<>', $material->id)->get();
        $exercises = Exercise::where('topic_id', $material->topic_id)->get();
        return view('participant.materials.show', compact('title', 'row', 'materials', 'exercises'));
    }
}

resources/views/admin/materials/create.blade.php
@extends('admin.default')
@section('title', $title)
@section('content')
    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header">
            <!--begin::Card title-->
            <div class="card-title">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <h3>{{ $title }}</h3>
                </div>
                <!--end::Search-->
            </div>
            <!--begin::Card title-->
        </div>
        <!--end::Card header-->

        {!! Form::model($row, ['route' => 'admin.materials.store','enctype' => 'multipart/form-data']) !!}
        @include('admin.materials.form', $row)
        {!! Form::close() !!}
    </div>
@endsection
@section('scripts')
@endsection

resources/views/admin/materials/edit.blade.php
@extends('admin.default')
@section('title', $title)
@section('content')
    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header">
            <!--begin::Card title-->
            <div class="card-title">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <h3>{{ $title }}</h3>
                </div>
                <!--end::Search-->
            </div>
            <!--begin::Card title-->
        </div>
        <!--end::Card header-->
    {!! Form::model($row, ['route' => ['admin.materials.update', $row], 'method' => 'PUT', 'enctype' => 'multipart/form-data']) !!}
    @include('admin.materials.form', $row)
    {!! Form::close() !!}
    <!--end::Datatable-->
    </div>
@endsection
@section('scripts')
@endsection

resources/views/admin/materials/show.blade.php
@extends('admin.default')
@section('title', $title)
@section('content')

    <div class="row">
        <div class="col-md-8">
            <!--begin::Card-->
            <div class="card">
                <!--begin::Card header-->
                <div class="card-header">
                    <!--begin::Card title-->
                    <div class="card-title">
                        <!--begin::Search-->
                        <div class="d-flex align-items-center position-relative my-1">
                            <h3>{{ $title }}</h3>
                        </div>
                        <!--end::Search-->
                    </div>


                    <div class="card">
                        <div class="card-body">
                            <div class="card-body">

                                {!! Form::model($row, ['route' => 'admin.exercises.store','enctype' => 'multipart/form-data']) !!}
                                <div class="row mb-6">
                                    {!! Form::label('name', 'Название', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                    <div class="col-lg-12">
                                        {!! Form::text('name', null, ['class' => 'form-control', 'disabled']) !!}
                                        @if($errors->has('name'))
                                            <div class="error-message">{{ $errors->first('name') }}</div>
                                        @endif
                                    </div>
                                </div>
                                <div class="row mb-6">
                                    {!! Form::label('description', 'Описание', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                    <div class="col-lg-12">
                                       <textarea class="form-control" name="description" id="description" disabled readonly>
                                            {{old('description') ?: $row->description }}
                                        </textarea>
                                        @if($errors->has('description'))
                                            <div class="error-message">{{ $errors->first('description') }}</div>
                                        @endif
                                    </div>
                                </div>
                                <div class="row mb-6">
                                    {!! Form::label('link', 'Ссылка на материал', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                    <div class="col-lg-12">
                                        {!! Form::text('link', null, ['class' => 'form-control', 'disabled']) !!}
                                        @if($errors->has('link'))
                                            <div class="error-message">{{ $errors->first('link') }}</div>
                                        @endif
                                    </div>
                                </div>
                                @if(isset($row->file))
                                <div class="row">
                                    {!! Form::label('deadline', 'Файл', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                    <div class="col-lg-12">
                                        <a class="current-attachment" href="{{ asset($row->file) }}">{{ $row->file }}</a>&nbsp;<a href="#" class="current-attachment"><span class="glyphicon glyphicon-remove-circle remove-attachment"></span></a>
                                    </div>
                                </div>
                                @endif
                                @if($row->type == 1)
                                    <div class="row">
                                        {!! Form::label('grade', 'Тип материала', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                        <div class="col-lg-12">
                                            {!! Form::text('grade', 'Индивидуальный материал', ['class' => 'form-control', 'disabled']) !!}
                                        </div>
                                    </div>
                                @else
                                    <div class="row">
                                        {!! Form::label('type', 'Тип материала', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                        <div class="col-lg-12">
                                            {!! Form::text('type', 'Командный материал', ['class' => 'form-control', 'disabled']) !!}
                                        </div>
                                    </div>
                                @endif
                                <!--end::Table-->
                                <div class="row">
                                    {!! Form::label('topic', 'Тема', ['class' => 'col-lg-12 col-form-label text-right']) !!}
                                    <div class="col-lg-12">
                                        {!! Form::text('topic', $row->getTopic(), ['class' => 'form-control', 'disabled']) !!}
                                    </div>
                                </div>
                                <!--end::Table-->

                                <div class="card-footer d-flex justify-content-end">
                                    <button type="reset" onclick="window.history.back();"
                                            class="btn btn-secondary me-2">Назад
                                    </button>
                                    <a href="{{route('admin.materials.edit', $row)}}" class="btn btn-primary">Редактировать</a>
                                </div>
                                {!! Form::close() !!}
                            </div>

                        </div>
                    </div>
                    <!--begin::Card title-->
                </div>
                <!--end::Card header-->

            </div>
        </div>
    </div>

@endsection

@section('scripts')

    <script>

        $('.btn-estimate').on('click', function () {
            let id = $(this).data('participant');

            $.ajax({
                url: "{{route('admin.exercise.participant.info', $row)}}",
                cache: false,
                method: 'POST',
                data: {
                    'participant_id': id
                }
            }).done(function (data) {
                console.log(data);
                $('#participantFullName').html(data['full_name']);
                if (data['file']) {
                    $('#participantExerciseFile').html('<a href="' + data['file'] + '" target="_blank">Ссылка на файл</a>');
                }
                $('#modal_exercise_participant_grade').append('<input type="hidden" name="participant_id" value="' + data['id'] + '">')
            });
        });


        @if(session('exercise-graded'))
        Swal.fire({
            html: "<div class='fw-bold fs-4'>Оценка на задание добавлена!</div>",
            icon: "success",
            buttonsStyling: false,
            confirmButtonText: "Продолжить",
            customClass: {
                confirmButton: "btn btn-primary"
            }
        });
        @elseif(session('exercise-not-graded'))
        Swal.fire({
            html: "<div class='fw-bold fs-4'>Задание еще не выполнено!</div>",
            icon: "error",
            buttonsStyling: false,
            confirmButtonText: "Продолжить",
            customClass: {
                confirmButton: "btn btn-primary"
            }
        });
        @endif

    </script>

@endsection

@push('scripts')
    <script src="{{asset('assets/plugins/custom/tinymce/tinymce.bundle.js')}}"></script>
    <script src="https://npmcdn.com/flatpickr/dist/flatpickr.min.js"></script>
    <script src="https://npmcdn.com/flatpickr/dist/l10n/ru.js"></script>

    <script>
        $(document).ready(function () {
            // tinyMCE editor
            tinyMCE.init({
                selector: '#description',
                plugins: "autoresize link lists media image  table textcolor lists code quickbars paste",
                menubar: false,
                toolbar: [
                    'undo redo | styleselect | bold italic link | alignleft aligncenter alignright alignjustify | outdent indent | code',
                ]
            });

            // date pick plugin
            $("#published_at").flatpickr({
                locale: "ru",
                enableTime: true,
                dateFormat: "Y-m-d H:i",
                time_24hr: true
            });
        });
    </script>
@endpush