routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix(LaravelLocalization::setLocale().'/admin')
    ->middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')
    ->group(function () {

        Route::group(['as' => 'admin.'], function() {

            Route::name('login')->get('login','Auth\LoginController@showLoginForm');
            Route::name('login.submit')->post('login', 'Auth\LoginController@login');
            Route::name('logout')->get('logout', 'Auth\LoginController@logout');

            Route::name('index')->get('', ['uses' => 'IndexController@index']);

            // applications
            Route::name('applications.index')->get('applications', ['uses' => 'IndexController@applications']);
            Route::name('applications.show')->get('applications/{participant}', ['uses' => 'IndexController@applicationsShow']);
            Route::name('applications.delete')->get('applications/{participant}/delete', ['uses' => 'IndexController@applicationsDelete']);

            // events
            Route::group(['as' => 'events.'], function() {
                Route::name('index')->get('/events', ['uses' => 'EventController@index']);
                Route::name('data')->get('/events/data', ['uses' => 'EventController@data']);
                Route::name('data.add')->post('/events/data/add', ['uses' => 'EventController@add']);
                Route::name('data.view')->get('/events/data/view/{id}', ['uses' => 'EventController@view']);
                Route::name('data.delete')->delete('/events/data/delete/{row}', ['uses' => 'EventController@delete']);
            });

            // Report
            Route::group(['as' => 'report.'], function() {
                Route::name('index')->get('/report', ['uses' => 'ReportController@index']);
                Route::name('ishtapp')->get('/report/ishtapp', ['uses' => 'ReportController@ishtapp']);
                Route::name('ishtapp.users')->get('/report/ishtapp/users', ['uses' => 'ReportController@ishtappUsers']);
                Route::name('ishtapp.companies')->get('/report/ishtapp/companies', ['uses' => 'ReportController@ishtappCompanies']);
                Route::name('ishtapp.opportunities')->get('/report/ishtapp/opportunities', ['uses' => 'ReportController@ishtappOpportunities']);
            });

            /*
             * ADMIN CONTROL
            */

            Route::resources([
                'roles' => 'RoleController',
                'permissions' => 'PermissionController',
                'topics' => 'TopicController',
                'exercises'=>'ExerciseController',
                'users' => 'UserController',
                'participants' => 'ParticipantController',
                'regions' => 'RegionController',
                'sdg' => 'SdgController',
                'teams' => 'TeamController',
                'materials' => 'MaterialController',
                'grades' => 'GradeController',
                'mail_messages' => 'MailMessageController',
            ]);

            // Participant Routes
            Route::name('participants.grade')->post('/participants/{participant}/grade', ['uses' => 'ParticipantController@grade']);

            // Team Routes
            Route::name('teams.delete_user')->get('teams/{team}/delete/{participant}', ['uses' => 'TeamController@delete_user']);
            Route::name('teams.particiantAdd')->post('teams/{team}/add/participant', ['uses' => 'TeamController@particiantAdd']);

            // Exercise Routes
            Route::name('exercise.participant.info')->post('exercise/{exercise}/participant/info', ['uses' => 'ExerciseController@participantInfo']);
            Route::name('exercise.team.info')->post('exercise/{exercise}/team/info', ['uses' => 'ExerciseController@teamInfo']);
            Route::name('exercise.participant.grade')->post('exercise/{exercise}/participant/grade', ['uses' => 'ExerciseController@participantGrade']);
            Route::name('exercise.team.grade')->post('exercise/{exercise}/team/grade', ['uses' => 'ExerciseController@teamGrade']);
            Route::name('exercise.create_')->get('exercise/{topic}/create', ['uses' => 'ExerciseController@create_']);

            // Materials Routes
            Route::name('material.create_')->get('material/{topic}/create', ['uses' => 'MaterialController@create_']);

            // Delete Routes
            Route::name('teams.delete')->get('teams/{team}/delete', ['uses' => 'TeamController@destroy']);
            Route::name('permissions.delete')->get('permissions/{permission}/delete', ['uses' => 'PermissionController@destroy']);
            Route::name('roles.delete')->get('roles/{role}/delete', ['uses' => 'RoleController@destroy']);
            Route::name('users.delete')->get('users/delete/{user}', ['uses' => 'UserController@destroy']);
            Route::name('participants.delete')->get('participants/delete/{participant}', ['uses' => 'ParticipantController@destroy']);
            Route::name('regions.delete')->get('regions/delete/{region}', ['uses' => 'RegionController@destroy']);
            Route::name('sdg.delete')->get('sdg/delete/{sdg}', ['uses' => 'SdgController@destroy']);
            Route::name('exercises.delete')->get('exercise/{exercise}/delete', ['uses' => 'ExerciseController@delete']);
            Route::name('topics.delete')->get('topic/{topic}/delete', ['uses' => 'TopicController@delete']);
            Route::name('materials.delete')->get('material/{material}/delete', ['uses' => 'MaterialController@delete']);
            Route::name('grades.delete')->get('grades/{grade}/delete', ['uses' => 'GradeController@delete']);
            Route::name('mail_messages.delete')->get('mail_messages/{mail_message}/delete', ['uses' => 'MailMessageController@delete']);

            // User [login, password] change
            Route::name('users.changeLogin')->put('users/changeLogin/{user}',  ['uses' => 'UserController@changeLogin']);
            Route::name('users.changePassword')->put('users/changePassword/{user}',  ['uses' => 'UserController@changePassword']);
            /*
             * LANDING PAGE CONTROL
            */
            Route::group(['as' => 'landing.'], function() {
                Route::resources([
                    'news' => 'NewsController',
                    'feedbacks' => 'FeedbackController',
                    'mentors' => 'MentorController'
                ]);

                Route::name('news.delete')->get('news/delete/{news}', ['uses' => 'NewsController@destroy']);
                Route::name('feedbacks.delete')->get('feedbacks/delete/{feedback}', ['uses' => 'FeedbackController@destroy']);
                Route::name('mentors.delete')->get('mentors/delete/{mentor}', ['uses' => 'MentorController@destroy']);
            });
        });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')->prefix(LaravelLocalization::setLocale())->group(function () {

    Route::name('web.index')->get('', 'IndexController@index');
    Route::name('web.news')->get('news', 'IndexController@news');
    Route::name('web.news.single')->get('news/single/{id}', 'IndexController@newsSingle');

    Route::name('participant.apply')->get('apply','IndexController@showApplyForm');
    Route::name('participant.apply.submit')->post('apply', 'IndexController@apply');

    Route::name('web.login')->get('login', 'IndexController@login');
    Route::name('web.login.submit')->post('login', 'IndexController@loginSubmit');

});

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Team extends Model
{
    use SearchableTrait;

    protected $table = 'teams';

    protected $guarded = ['id'];

    protected $searchable = [
        'columns' => [
            'teams.name' => 10
        ]
    ];

    protected $casts = [
        'sdgs' => 'array',
    ];

    // relations
    public function region(){
        return $this->belongsTo(Region::class, 'region_id');
    }
    public function sdg(){
        return $this->belongsTo(Sdg::class, 'sdg_id');
    }
    public function mentor(){
        return $this->hasOne(User::class, 'team_id');
    }
    public function leader(){
        return $this->belongsTo(Participant::class, 'leader_id');
    }
    public function participants()
    {
        return $this->hasMany(Participant::class, 'team_id');
    }

    public function exercises()
    {
        return $this->hasMany(TeamExercise::class, 'team_id');
    }

    public function lider(){
        if ($this->leader_id){
            $participant = Participant::findOrFail($this->leader_id);
            if ($participant){
                return $participant->id;
            }
        }
        return null;
    }

    public function exercise($exercise)
    {
        if($exercise){
            return TeamExercise::where('exercise_id', $exercise)->where('team_id', $this->id)->first();
        }
        return false;
    }

    // attributes
    public function sdgsList()
    {
        $lang = app()->getLocale();
        if($this->sdgs){
            $sdgs = '<ul class="list-unstyled">';
            foreach ($this->sdgs as $key => $row) {
                $sdg = Sdg::find($row);
                $sdgs .= '<li>- '.$sdg->getName($lang).'</li>';
            }
            $sdgs .= '</ul>';
            return $sdgs;
        } else {
            return '-';
        }
    }


}

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Participant;
use App\Models\Region;
use App\Models\Sdg;
use App\Models\Team;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TeamController extends Controller
{
    function __construct()
    {
         $this->middleware('permission:teams-index');
         $this->middleware('permission:teams-create', ['only' => ['create','store']]);
         $this->middleware('permission:teams-update', ['only' => ['edit','update']]);
         $this->middleware('permission:teams-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $title = 'Команды';

        if(request()->ajax()){
            $data = Team::query();
            if (request()->search['value']) {
                $data = $data->search(request()->search['value']);
            }
            $data = $data->get();
            return datatables()->of($data)
                ->addIndexColumn()
                ->addColumn('actions', function ($row) {
                    return '
                        <a href="'.route('admin.teams.edit', $row).'" class="btn btn-sm btn-icon btn-light btn-active-light-success" title="Редактировать">
                            <i class="las la-pen fs-3 text-success"></i>
                        </a>
                        <a href="'.route('admin.teams.delete', $row).'" class="btn btn-sm btn-icon btn-light btn-active-light-danger" title="Удалить">
                            <i class="las la-times fs-4 text-danger"></i>
                        </a>
                        <a href="'.route('admin.teams.show', $row).'" class="btn btn-sm btn-icon btn-light btn-active-light-danger" title="Посмотреть">
                            <i class="las la-eye fs-4 text-warning"></i>
                        </a>
                    ';
                })
                ->addColumn('participants_count', function ($row) {
                    return $row->participants->count();
                })
                ->addColumn('region', function ($row) {
                    return $row->region ? $row->region->name_ru : '-';
                })
                ->addColumn('mentor', function ($row) {
                    return $row->mentor ? $row->mentor->full_name : '-';
                })
                ->rawColumns(['actions'])
                ->make(true);
        }

        return view('admin.teams.index', compact('title'));
    }

    public function create()
    {
        $lang = app()->getLocale();
        $title = 'Форма создания команды';
        $row = new Team();
        $regions = Region::pluck('name_ru', 'id')->toArray();
        $participants = Participant::where('team_id', null)->pluck('name', 'id')->toArray();
        $participants_selected = null;
        $sdg = $lang == 'ru' ? Sdg::pluck('name_ru', 'id')->toArray() : Sdg::pluck('name', 'id')->toArray();
        $mentors = User::role('Ментор')->get()->pluck('full_name', 'id')->toArray();
        return view('admin.teams.create', compact('title', 'row', 'regions', 'participants', 'participants_selected', 'sdg', 'mentors'));
    }

    public function store(Request $request)
    {
        $data = $request->only('name', 'description', 'region_id', 'sdg_id');
        $request->validate([
            'name'   => 'required',
            'description' => 'required',
            'region_id' => 'required',
            'sdgs' => 'required',
        ]);

        $participants_id = $request['participants'];
        $team = Team::create($data);

        if ($participants_id){
            foreach ($participants_id as $item) {
                $p = Participant::findOrFail($item);
                $p->team_id = $team->id;
                $p->save();
            }
        }

        if ($request->mentor_id){
            $mentor = User::findOrFail($request->mentor_id);
            $mentor->team_id = $team->id;
            $mentor->save();
        }

        return redirect(route('admin.teams.index'));
    }

    public function show(Team $team){
        $i = 1;
        $row = $team;
        $title = 'Команда';
        $participants = Participant::where('team_id', $team->id)->get();

        $participants_select = Participant::where('team_id', null)->orWhere('team_id', $team->id)->pluck('name', 'id')->toArray();
        $participants_selected = $row->participants ? $row->participants->pluck('id')->toArray() : [];

        return view('admin.teams.show', compact('row', 'title', 'participants', 'participants_select', 'participants_selected', 'i'));
    }

    public function edit(Team $team)
    {
        $lang = app()->getLocale();
        $title = 'Редактировать';
        $row = $team;
        $regions = Region::pluck('name_ru', 'id')->toArray();
        $participants = Participant::where('team_id', '=', null)->orWhere('team_id', $team->id)->pluck('name', 'id')->toArray();
        $participants_selected = Participant::where('team_id', $team->id)->orWhere('team_id', $team->id)->pluck('id')->toArray();
        $sdg = $lang == 'ru' ? Sdg::pluck('name_ru', 'id')->toArray() : Sdg::pluck('name', 'id')->toArray();
        $mentors = User::role('Ментор')->get()->pluck('full_name', 'id')->toArray();
        return view('admin.teams.edit', compact('title', 'row', 'regions', 'participants', 'participants_selected', 'sdg', 'mentors'));
    }

    public function update(Request $request, Team $team)
    {
        $data = $request->only('name', 'description', 'region_id', 'sdgs');
        $request->validate([
            'name'   => 'required',
            'description' => 'required',
            'region_id' => 'required',
            'sdgs' => 'required',
        ]);
        $team->update($data);

        $participants_id = $request['participants'];
        $sql = 'UPDATE participants SET team_id = null WHERE team_id = ' . strval($team->id);
        DB::statement($sql);
        if ($participants_id) {
            foreach ($participants_id as $item) {
                $p = Participant::findOrFail($item);
                $p->team_id = $team->id;
                $p->save();
            }
        }

        if ($request->mentor_id && $team->mentor_id != $request->mentor_id){
            if($team->mentor){
                $team->mentor->team_id = null;
                $team->mentor->save();
            }
            $mentor = User::findOrFail($request->mentor_id);
            $mentor->team_id = $team->id;
            $mentor->save();
        }

        return redirect(route('admin.teams.show', $team));
    }

    public function destroy(Team $team)
    {
        $team->delete();
        return redirect(route('admin.teams.index'));
    }

    public function particiantAdd(Request $request, Team $team){
        $participants_id = $request['participants'];
        $sql = 'UPDATE participants SET team_id = null WHERE team_id = ' . strval($team->id);
        DB::statement($sql);
        if ($participants_id) {
            foreach ($participants_id as $item) {
                $p = Participant::findOrFail($item);
                $p->team_id = $team->id;
                $p->save();
            }
        }
        return redirect(route('admin.teams.show', $team));
    }

    public function delete_user(Team $team, Participant $participant)
    {
        $participant->team_id = null;
        $participant->save();
        return redirect(route('admin.teams.show', $team));
    }
}

resources/views/admin/teams/create.blade.php
@extends('admin.default')

@section('title', $title)


@section('content')

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header">
            <!--begin::Card title-->
            <div class="card-title">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <h3>{{ $title }}</h3>
                </div>
                <!--end::Search-->
            </div>
            <!--begin::Card title-->
        </div>
        <!--end::Card header-->

        {!! Form::model($row, ['route' => 'admin.teams.store','enctype' => 'multipart/form-data']) !!}
        @include('admin.teams.form', $row)
        {!! Form::close() !!}

    </div>

@endsection

@section('scripts')

@endsection

resources/views/admin/teams/show.blade.php
@extends('admin.default')

@section('title', $title)

@section('content')

    <div class="d-flex flex-column flex-lg-row">
        <!--begin::Sidebar-->
        <div class="flex-column flex-lg-row-auto w-lg-300px w-xl-400px mb-10">
            <!--begin::Card-->
            <div class="card mb-5 mb-xl-8">
                <!--begin::Card body-->
                <div class="card-body">
                    <!--begin::Summary-->
                    <!--begin::User Info-->
                    <div class="d-flex flex-center flex-column py-5">
                        <!--begin::Avatar-->
                        <div class="symbol symbol-100px symbol-circle mb-7">
                            <img src="{{asset('assets/media/avatars/blank.png')}}" alt="image">
                        </div>
                        <!--end::Avatar-->
                        <!--begin::Name-->
                        <a href="#" class="fs-3 text-gray-800 text-hover-primary fw-bolder mb-3">{{ $row->name }}</a>
                        <!--end::Name-->
                        <!--begin::Position-->
                        <div class="mb-9">
                            <!--begin::Badge-->
                            <!--begin::Badge-->
                        </div>
                        <!--end::Position-->
                    </div>
                    <!--end::User Info-->
                    <!--end::Summary-->
                    <!--begin::Details toggle-->
                    <div class="d-flex flex-stack fs-4 py-3">
                        <div class="fw-bolder rotate collapsible" data-bs-toggle="collapse" href="#kt_user_view_details" role="button" aria-expanded="false" aria-controls="kt_user_view_details">
                            Информация
                        </div>
                        <span>
                            <a href="{{ route('admin.teams.edit', $row) }}" class="btn btn-sm btn-light-primary">
                                Редактировать
                            </a>
                        </span>
                    </div>
                    <!--end::Details toggle-->
                    <div class="separator"></div>
                    <!--begin::Details content-->
                    <div id="kt_user_view_details" class="collapse show">
                        <div class="pb-5 fs-6">
                            <!--begin::Details item-->
                            <div class="fw-boldest mt-5">Название команды</div>
                            <div class="text-gray-600">{{ $row->name }}</div>
                            <!--begin::Details item-->
                            <div class="fw-boldest mt-5">Описание команды</div>
                            <div class="text-gray-600">{{ $row->description }}</div>
                            <!--begin::Details item-->
                            <div class="fw-boldest mt-5">Регион</div>
                            <div class="text-gray-600">{{ $row->region ? $row->region->getName(app()->getLocale()) : '-' }}</div>
                            <!--begin::Details item-->
                            <div class="fw-boldest mt-5">Ментор</div>
                            <div class="text-gray-600">{{ $row->mentor ? $row->mentor->full_name : '-' }}</div>
                        </div>
                    </div>
                    <!--end::Details content-->
                    <div class="separator"></div>
                    <!--begin::Details toggle-->
                    <div class="d-flex flex-stack fs-4 py-6">
                        <span>
                            <a href="{{ route('admin.teams.delete', $row) }}" class="btn btn-sm btn-danger">
                                Удалить
                            </a>
                        </span>
                    </div>
                    <!--end::Details toggle-->
                </div>
                <!--end::Card body-->
            </div>
            <!--end::Card-->
        </div>
        <!--end::Sidebar-->
        <!--begin::Content-->
        <div class="flex-lg-row-fluid ms-lg-15">

            <div class="card mb-6 mb-xl-9">
                <!--begin::Card header-->
                <div class="card-header">
                    <h3 class="card-title">Состав команды</h3>
                    <div class="card-toolbar">
                        <a href="#" class="btn btn-sm btn-success" data-bs-toggle="modal" data-bs-target="#kt_modal_update_details">
                            <!--begin::Svg Icon | path: icons/duotune/arrows/arr075.svg-->
                            <span class="svg-icon svg-icon-2">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                    <rect opacity="0.5" x="11.364" y="20.364" width="16" height="2" rx="1"  transform="rotate(-90 11.364 20.364)" fill="black"></rect>
                                    <rect x="4.36396" y="11.364" width="16" height="2" rx="1" fill="black"></rect>
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                            Добавить участников
                        </a>
                    </div>
                </div>
                <!--end::Card header-->
                <!--begin::Card body-->
                <div class="card-body pb-5">
                    <!--begin::Table wrapper-->
                    <div class="table-responsive">
                        <!--begin::Table-->
                        <table class="table align-middle table-row-dashed gy-5" id="kt_table_users_login_session">
                            <!--begin::Table head-->
                            <thead class="border-bottom border-gray-200 fs-7 fw-bolder">
                            <!--begin::Table row-->
                            <tr class="text-start text-muted text-uppercase gs-0">
                                <th class="w-40px">№</th>
                                <th>ФИО</th>
                                <th>Телефон</th>
                                <th>Email адресс</th>
                                <th class="min-w-125px text-end">Действия</th>
                            </tr>
                            <!--end::Table row-->
                            </thead>
                            <!--end::Table head-->
                            <!--begin::Table body-->
                            <tbody class="fs-6 fw-bold text-gray-600">
                            @foreach($participants as $p)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $p->name }} {{ $p->lastname }}</td>
                                    <td>{{ $p->phone }}</td>
                                    <td>{{ $p->email }}</td>
                                    <td class="text-end">
                                        <a href="{{ route('admin.teams.delete_user', [$row, $p->id]) }}" class="btn btn-sm btn-light-danger" title="Удалить">
                                            Удалить
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <!--end::Table body-->
                        </table>

                        <!--end::Table-->
                    </div>
                    <!--end::Table wrapper-->
                </div>

                <!--end::Card body-->
            </div>

        </div>
        <!--end::Content-->
    </div>

    <!--begin::Modal-->
    <div class="modal fade" id="kt_modal_update_details" tabindex="-1" aria-hidden="true">
        <!--begin::Modal dialog-->
        <div class="modal-dialog modal-dialog-centered mw-650px">
            <!--begin::Modal content-->
            <div class="modal-content">
                <!--begin::Form-->
                <form class="form" action="{{route('admin.teams.particiantAdd', $row)}}" id="kt_modal_update_user_form"
                      method="POST" enctype="multipart/form-data">
                @csrf
                <!--begin::Modal header-->
                    <div class="modal-header px-lg-12" id="kt_modal_update_user_header">
                        <!--begin::Modal title-->
                        <h2 class="fw-bolder">Добавить участников</h2>
                        <!--end::Modal title-->
                        <!--begin::Close-->
                        <div class="btn btn-icon btn-sm btn-active-light-primary ms-2" data-bs-dismiss="modal" aria-label="Close">
                            <span class="svg-icon svg-icon-2x">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                     fill="none">
                                    <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1"
                                          transform="rotate(-45 6 17.3137)" fill="black"/>
                                    <rect x="7.41422" y="6" width="16" height="2" rx="1"
                                          transform="rotate(45 7.41422 6)" fill="black"/>
                                </svg>
                            </span>
                        </div>
                        <!--end::Close-->
                    </div>
                    <!--end::Modal header-->
                    <!--begin::Modal body-->
                    <div class="modal-body py-10 px-lg-12">
                        <!--begin::Scroll-->
                        <div class="d-flex flex-column scroll-y me-n7 pe-7" id="kt_modal_update_user_scroll"
                             data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}"
                             data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_update_user_header"
                             data-kt-scroll-wrappers="#kt_modal_update_user_scroll" data-kt-scroll-offset="300px">
                            <!--begin::User form-->
                            <div id="kt_modal_update_user_user_info">
                                <!--begin::Input group-->
                                <div class="fv-row mb-7">
                                    <!--begin::Label-->
                                    <label class="fs-6 fw-bold mb-2">
                                        <span>Участники</span>
                                    </label>
                                    <!--end::Label-->
                                    <!--begin::Input-->
                                    {!! Form::select('participants', $participants_select, $participants_selected,['class' => 'form-select', 'data-control'=>'select2', 'multiple'=>'multiple','name'=>'participants[]', 'data-placeholder'=>'Выбрать']) !!}
                                    @if($errors->has('participants'))
                                        <div class="error-message">{{ $errors->first('participants') }}</div>
                                @endif
                                <!--end::Input-->
                                </div>
                                <!--end::Input-->
                            </div>
                            <!--end::Input group-->
                        </div>
                        <!--end::User form-->
                    </div>
                    <!--end::Scroll-->
                    <!--end::Modal body-->
                    <!--begin::Modal footer-->
                    <div class="modal-footer flex-center">
                        <!--begin::Button-->
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button>
                        <!--end::Button-->
                        <!--begin::Button-->
                        <button type="submit" class="btn btn-primary" data-kt-users-modal-action="submit">Сохранить</button>
                        <!--end::Button-->
                    </div>
                    <!--end::Modal footer-->
                </form>
                <!--end::Form-->
            </div>
            <!--end::Modal - Update user details-->
        </div>
    </div>

@endsection

@section('scripts')

    <script>

        $("#datepicker_date").flatpickr({
            dateFormat: "d-m-Y",
        });

        @if(session('profile-updated'))
        Swal.fire({
            html: "<div class='fw-bold fs-4'>Изменения сохранены!</div>",
            icon: "success",
            buttonsStyling: false,
            confirmButtonText: "Продолжить",
            customClass: {
                confirmButton: "btn btn-primary"
            }
        });
        @endif

    </script>

@endsection