routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix(LaravelLocalization::setLocale().'/admin')
    ->middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')
    ->group(function () {

        Route::group(['as' => 'admin.'], function() {

            Route::name('login')->get('login','Auth\LoginController@showLoginForm');
            Route::name('login.submit')->post('login', 'Auth\LoginController@login');
            Route::name('logout')->get('logout', 'Auth\LoginController@logout');

            Route::name('index')->get('', ['uses' => 'IndexController@index']);

            // applications
            Route::name('applications.index')->get('applications', ['uses' => 'IndexController@applications']);
            Route::name('applications.show')->get('applications/{participant}', ['uses' => 'IndexController@applicationsShow']);
            Route::name('applications.delete')->get('applications/{participant}/delete', ['uses' => 'IndexController@applicationsDelete']);

            // events
            Route::group(['as' => 'events.'], function() {
                Route::name('index')->get('/events', ['uses' => 'EventController@index']);
                Route::name('data')->get('/events/data', ['uses' => 'EventController@data']);
                Route::name('data.add')->post('/events/data/add', ['uses' => 'EventController@add']);
                Route::name('data.view')->get('/events/data/view/{id}', ['uses' => 'EventController@view']);
                Route::name('data.delete')->delete('/events/data/delete/{row}', ['uses' => 'EventController@delete']);
            });

            // Report
            Route::group(['as' => 'report.'], function() {
                Route::name('index')->get('/report', ['uses' => 'ReportController@index']);
                Route::name('ishtapp')->get('/report/ishtapp', ['uses' => 'ReportController@ishtapp']);
                Route::name('ishtapp.users')->get('/report/ishtapp/users', ['uses' => 'ReportController@ishtappUsers']);
                Route::name('ishtapp.companies')->get('/report/ishtapp/companies', ['uses' => 'ReportController@ishtappCompanies']);
                Route::name('ishtapp.opportunities')->get('/report/ishtapp/opportunities', ['uses' => 'ReportController@ishtappOpportunities']);
            });

            /*
             * ADMIN CONTROL
            */

            Route::resources([
                'roles' => 'RoleController',
                'permissions' => 'PermissionController',
                'topics' => 'TopicController',
                'exercises'=>'ExerciseController',
                'users' => 'UserController',
                'participants' => 'ParticipantController',
                'regions' => 'RegionController',
                'sdg' => 'SdgController',
                'teams' => 'TeamController',
                'materials' => 'MaterialController',
                'grades' => 'GradeController',
                'mail_messages' => 'MailMessageController',
            ]);

            // Participant Routes
            Route::name('participants.grade')->post('/participants/{participant}/grade', ['uses' => 'ParticipantController@grade']);

            // Team Routes
            Route::name('teams.delete_user')->get('teams/{team}/delete/{participant}', ['uses' => 'TeamController@delete_user']);
            Route::name('teams.particiantAdd')->post('teams/{team}/add/participant', ['uses' => 'TeamController@particiantAdd']);

            // Exercise Routes
            Route::name('exercise.participant.info')->post('exercise/{exercise}/participant/info', ['uses' => 'ExerciseController@participantInfo']);
            Route::name('exercise.team.info')->post('exercise/{exercise}/team/info', ['uses' => 'ExerciseController@teamInfo']);
            Route::name('exercise.participant.grade')->post('exercise/{exercise}/participant/grade', ['uses' => 'ExerciseController@participantGrade']);
            Route::name('exercise.team.grade')->post('exercise/{exercise}/team/grade', ['uses' => 'ExerciseController@teamGrade']);
            Route::name('exercise.create_')->get('exercise/{topic}/create', ['uses' => 'ExerciseController@create_']);

            // Materials Routes
            Route::name('material.create_')->get('material/{topic}/create', ['uses' => 'MaterialController@create_']);

            // Delete Routes
            Route::name('teams.delete')->get('teams/{team}/delete', ['uses' => 'TeamController@destroy']);
            Route::name('permissions.delete')->get('permissions/{permission}/delete', ['uses' => 'PermissionController@destroy']);
            Route::name('roles.delete')->get('roles/{role}/delete', ['uses' => 'RoleController@destroy']);
            Route::name('users.delete')->get('users/delete/{user}', ['uses' => 'UserController@destroy']);
            Route::name('participants.delete')->get('participants/delete/{participant}', ['uses' => 'ParticipantController@destroy']);
            Route::name('regions.delete')->get('regions/delete/{region}', ['uses' => 'RegionController@destroy']);
            Route::name('sdg.delete')->get('sdg/delete/{sdg}', ['uses' => 'SdgController@destroy']);
            Route::name('exercises.delete')->get('exercise/{exercise}/delete', ['uses' => 'ExerciseController@delete']);
            Route::name('topics.delete')->get('topic/{topic}/delete', ['uses' => 'TopicController@delete']);
            Route::name('materials.delete')->get('material/{material}/delete', ['uses' => 'MaterialController@delete']);
            Route::name('grades.delete')->get('grades/{grade}/delete', ['uses' => 'GradeController@delete']);
            Route::name('mail_messages.delete')->get('mail_messages/{mail_message}/delete', ['uses' => 'MailMessageController@delete']);

            // User [login, password] change
            Route::name('users.changeLogin')->put('users/changeLogin/{user}',  ['uses' => 'UserController@changeLogin']);
            Route::name('users.changePassword')->put('users/changePassword/{user}',  ['uses' => 'UserController@changePassword']);
            /*
             * LANDING PAGE CONTROL
            */
            Route::group(['as' => 'landing.'], function() {
                Route::resources([
                    'news' => 'NewsController',
                    'feedbacks' => 'FeedbackController',
                    'mentors' => 'MentorController'
                ]);

                Route::name('news.delete')->get('news/delete/{news}', ['uses' => 'NewsController@destroy']);
                Route::name('feedbacks.delete')->get('feedbacks/delete/{feedback}', ['uses' => 'FeedbackController@destroy']);
                Route::name('mentors.delete')->get('mentors/delete/{mentor}', ['uses' => 'MentorController@destroy']);
            });
        });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('localeSessionRedirect', 'localizationRedirect', 'localeViewPath')->prefix(LaravelLocalization::setLocale())->group(function () {

    Route::name('web.index')->get('', 'IndexController@index');
    Route::name('web.news')->get('news', 'IndexController@news');
    Route::name('web.news.single')->get('news/single/{id}', 'IndexController@newsSingle');

    Route::name('participant.apply')->get('apply','IndexController@showApplyForm');
    Route::name('participant.apply.submit')->post('apply', 'IndexController@apply');

    Route::name('web.login')->get('login', 'IndexController@login');
    Route::name('web.login.submit')->post('login', 'IndexController@loginSubmit');

});

app/Http/Controllers/Admin/ReportController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Models\Exercise;
use App\Models\IshtappUser;
use App\Models\IshtappVacancy;
use App\Models\Participant;
use App\Models\ParticipantExercise;
use App\Models\Region;
use App\Models\Team;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\DataTables;

class ReportController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:report-index');
    }

    public function index()
    {
        $regions = Region::get()->sortBy('name_ru')->pluck('name_ru', 'id')->toArray();
        $participants = Participant::where('status', true)->get()->sortBy('full_name')->pluck('full_name', 'id')->toArray();
        $teams = Team::get()->sortBy('name')->pluck('name', 'id')->toArray();

        $exercises = Exercise::query();
        if(request()->period){
            $divide = explode(" - ",request()->period);
            $start = $divide[0];
            $end = $divide[1];
            $date_start = Carbon::create($start)->format('d-m-Y');
            $date_end = Carbon::create($end)->format('d-m-Y');
            $exercises = $exercises->whereBetween('deadline', [$date_start, $date_end]);
        }
        $exercises = $exercises->get();

        $data = Participant::query();
        $data = $data->where('status', true);
        if(request()->participant){
            $data = $data->where('id', request()->participant);
        }
        if(request()->region){
            $data = $data->where('region_id', request()->region);
        }
        if(request()->team){
            $data = $data->where('team_id', request()->team);
        }
        $data = $data->get();

        return view('admin.report.index', compact('regions', 'participants', 'teams', 'exercises', 'data'));
    }

    public function ishtapp()
    {
        $ishtapp_users = IshtappUser::where('type', 'USER')->where('is_product_lab_user', true)->orderBy('created_at', 'desc')->get();
        $ishtapp_companies = IshtappUser::where('type', 'COMPANY')->join('vacancies', 'users.id', '=', 'vacancies.company_id')->where('vacancies.is_product_lab_vacancy', true) ->select('users.*')->groupBy('users.id')->orderBy('created_at', 'desc')->get();
        $ishtapp_vacancies = IshtappVacancy::where('is_product_lab_vacancy', true)->orderBy('created_at', 'desc')->get();
        return view('admin.report.ishtapp', compact('ishtapp_companies', 'ishtapp_users', 'ishtapp_vacancies'));
    }

    public function ishtappUsers()
    {
        $title = 'ishtapp - Пользователи';

        if(request()->ajax()) {

            $data = IshtappUser::where('type', 'USER')->where('is_product_lab_user', true)->orderBy('created_at', 'desc')->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('birth_date', function ($row) { return date('d-m-Y', strtotime($row->birth_date)); })
                ->addColumn('region', function ($row) { return $row->getRegion ? $row->getRegion->nameRu : '-'; })
                ->make(true);
        }

        return view('admin.report.ishtapp-users', compact('title'));
    }

    public function ishtappCompanies()
    {
        $title = 'ishtapp - Компании';

        if(request()->ajax()) {

//            $data = IshtappUser::where('type', 'COMPANY')
//                ->leftJoin('vacancies', 'users.id', '=', 'vacancies.company_id')
//                ->where('vacancies.is_product_lab_vacancy', true)
//                ->select('users.*')
//                ->orderBy('created_at', 'desc')
//                ->get();

            $data = IshtappUser::where('type', 'COMPANY')
                ->whereExists(function ($query) {
                    $query->select(DB::raw(1))
                        ->from('vacancies')
                        ->whereColumn('vacancies.company_id', 'users.id')
                        ->where('vacancies.is_product_lab_vacancy', true);
                })
                ->orderBy('created_at', 'desc')
                ->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('region', function ($row) { return $row->getRegion ? $row->getRegion->nameRu : '-'; })
                ->addColumn('opportunities', function ($row) { return $row->getOpportunities->count(); })
                ->make(true);
        }

        return view('admin.report.ishtapp-companies', compact('title'));
    }

    public function ishtappOpportunities()
    {
        $title = 'ishtapp - Возможности';

        if(request()->ajax()) {

            $data = IshtappVacancy::where('is_product_lab_vacancy', true)->orderBy('created_at', 'desc')->get();

            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('company', function ($row) { return $row->getCompany ? $row->getCompany->name : '-'; })
                ->addColumn('opportunity', function ($row) { return $row->getOpportunity ? $row->getOpportunity->name_ru : '-'; })
                ->addColumn('region', function ($row) { return $row->getRegion ? $row->getRegion->nameRu : '-'; })
                ->make(true);
        }

        return view('admin.report.ishtapp-opportunities', compact('title'));
    }
}

resources/views/admin/report/ishtapp-companies.blade.php
@extends('admin.default')

@section('title', $title)

@section('pre_styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-6">
            <!--begin::Card title-->
            <div class="card-title">
                {{$title}}
            </div>
            <!--end::Card title-->
            <!--begin::Card toolbar-->
            <div class="card-toolbar">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                    <span class="svg-icon svg-icon-1 position-absolute ms-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <input type="text" id="search_handler" class="form-control w-250px ps-14" placeholder="Поиск" />
                </div>
                <!--end::Search-->
            </div>
            <!--end::Card toolbar-->
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        <div class="card-body py-4 position-relative">
            <!--begin: Datatable-->
            <table id="dataTable" class="table align-middle table-row-dashed table-row-dashed fs-6 gy-5">
                <thead>
                <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                    <th class="w-50px">№</th>
                    <th>ФИО</th>
                    <th>Эл.адрес</th>
                    <th>Регион</th>
                    <th>Кол-во возможностей</th>
                </tr>
                </thead>
                <tbody class="text-gray-600 fw-bold"></tbody>
            </table>
            <!--end: Datatable-->
        </div>
        <!--end::Card body-->
    </div>

@endsection

@section('scripts')

    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}"></script>

    <script>
        let table = $('#dataTable').DataTable({
            dom: 'tr'+
                '<"row"<"col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start"li><"col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end dataTables_pager"p>>',
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.report.ishtapp.companies') }}',
                data: function(d) {
                }
            },
            columns: [
                { data: 'DT_RowIndex'},
                { data: 'name'},
                { data: 'email'},
                { data: 'region'},
                { data: 'opportunities'},
            ],
            order: [[ 0, "desc" ]],
            pageLength: 20,
            lengthMenu: ['20', '30', '40', '50', '100'],
            language: {
                "url": "{{asset('assets/js/russian.json')}}"
            },
        });

        // Search Datatable
        const filterSearch = $('#search_handler');

        filterSearch.keyup(function (e) {
            table.search(e.target.value).draw();
        });

    </script>
@endsection

resources/views/admin/report/ishtapp-opportunities.blade.php
@extends('admin.default')

@section('title', $title)

@section('pre_styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-6">
            <!--begin::Card title-->
            <div class="card-title">
                {{$title}}
            </div>
            <!--end::Card title-->
            <!--begin::Card toolbar-->
            <div class="card-toolbar">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                    <span class="svg-icon svg-icon-1 position-absolute ms-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <input type="text" id="search_handler" class="form-control w-250px ps-14" placeholder="Поиск" />
                </div>
                <!--end::Search-->
            </div>
            <!--end::Card toolbar-->
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        <div class="card-body py-4 position-relative">
            <!--begin: Datatable-->
            <table id="dataTable" class="table align-middle table-row-dashed table-row-dashed fs-6 gy-5">
                <thead>
                <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                    <th class="w-50px">№</th>
                    <th>Название</th>
                    <th>Компания</th>
                    <th>Тип возможности</th>
                    <th>Регион</th>
                </tr>
                </thead>
                <tbody class="text-gray-600 fw-bold"></tbody>
            </table>
            <!--end: Datatable-->
        </div>
        <!--end::Card body-->
    </div>

@endsection

@section('scripts')

    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}"></script>

    <script>
        let table = $('#dataTable').DataTable({
            dom: 'tr'+
                '<"row"<"col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start"li><"col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end dataTables_pager"p>>',
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.report.ishtapp.opportunities') }}',
                data: function(d) {
                }
            },
            columns: [
                { data: 'DT_RowIndex'},
                { data: 'name'},
                { data: 'company'},
                { data: 'opportunity'},
                { data: 'region'},
            ],
            order: [[ 0, "desc" ]],
            pageLength: 20,
            lengthMenu: ['20', '30', '40', '50', '100'],
            language: {
                "url": "{{asset('assets/js/russian.json')}}"
            },
        });

        // Search Datatable
        const filterSearch = $('#search_handler');

        filterSearch.keyup(function (e) {
            table.search(e.target.value).draw();
        });

    </script>
@endsection

resources/views/admin/report/ishtapp-users.blade.php
@extends('admin.default')

@section('title', $title)

@section('pre_styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!--begin::Card-->
    <div class="card">
        <!--begin::Card header-->
        <div class="card-header border-0 pt-6">
            <!--begin::Card title-->
            <div class="card-title">
                {{$title}}
            </div>
            <!--end::Card title-->
            <!--begin::Card toolbar-->
            <div class="card-toolbar">
                <!--begin::Search-->
                <div class="d-flex align-items-center position-relative my-1">
                    <!--begin::Svg Icon | path: icons/duotune/general/gen021.svg-->
                    <span class="svg-icon svg-icon-1 position-absolute ms-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>
                    <!--end::Svg Icon-->
                    <input type="text" id="search_handler" class="form-control w-250px ps-14" placeholder="Поиск" />
                </div>
                <!--end::Search-->
            </div>
            <!--end::Card toolbar-->
        </div>
        <!--end::Card header-->
        <!--begin::Card body-->
        <div class="card-body py-4 position-relative">
            <!--begin: Datatable-->
            <table id="dataTable" class="table align-middle table-row-dashed table-row-dashed fs-6 gy-5">
                <thead>
                <tr class="text-start text-gray-400 fw-bolder fs-7 text-uppercase gs-0">
                    <th class="w-50px">№</th>
                    <th>ФИО</th>
                    <th>Эл.адрес</th>
                    <th>Дата рождения</th>
                    <th>Регион</th>
                </tr>
                </thead>
                <tbody class="text-gray-600 fw-bold"></tbody>
            </table>
            <!--end: Datatable-->
        </div>
        <!--end::Card body-->
    </div>

@endsection

@section('scripts')

    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}"></script>

    <script>
        let table = $('#dataTable').DataTable({
            dom: 'tr'+
                '<"row"<"col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start"li><"col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end dataTables_pager"p>>',
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.report.ishtapp.users') }}',
                data: function(d) {
                }
            },
            columns: [
                { data: 'DT_RowIndex'},
                { data: 'name'},
                { data: 'email'},
                { data: 'birth_date'},
                { data: 'region'},
            ],
            order: [[ 0, "desc" ]],
            pageLength: 20,
            lengthMenu: ['20', '30', '40', '50', '100'],
            language: {
                "url": "{{asset('assets/js/russian.json')}}"
            },
        });

        // Search Datatable
        const filterSearch = $('#search_handler');

        filterSearch.keyup(function (e) {
            table.search(e.target.value).draw();
        });

    </script>
@endsection

resources/views/admin/report/ishtapp.blade.php
@extends('admin.default')

@section('title', 'Отчет по приложению ishtapp')

@section('content')

<div class="row">
    <div class="col-md-4">
        <div class="card bg-primary shadow-sm card-md-stretch-50 mb-md-8">
            <!--begin::Body-->
            <div class="card-body d-flex flex-column justify-content-center">
                <!--begin::Svg Icon | path: icons/duotune/graphs/gra007.svg-->
                <span class="svg-icon svg-icon-white svg-icon-5x ms-n1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <path d="M16.0173 9H15.3945C14.2833 9 13.263 9.61425 12.7431 10.5963L12.154 11.7091C12.0645 11.8781 12.1072 12.0868 12.2559 12.2071L12.6402 12.5183C13.2631 13.0225 13.7556 13.6691 14.0764 14.4035L14.2321 14.7601C14.2957 14.9058 14.4396 15 14.5987 15H18.6747C19.7297 15 20.4057 13.8774 19.912 12.945L18.6686 10.5963C18.1487 9.61425 17.1285 9 16.0173 9Z" fill="black"/>
                            <rect opacity="0.3" x="14" y="4" width="4" height="4" rx="2" fill="black"/>
                            <path d="M4.65486 14.8559C5.40389 13.1224 7.11161 12 9 12C10.8884 12 12.5961 13.1224 13.3451 14.8559L14.793 18.2067C15.3636 19.5271 14.3955 21 12.9571 21H5.04292C3.60453 21 2.63644 19.5271 3.20698 18.2067L4.65486 14.8559Z" fill="black"/>
                            <rect opacity="0.3" x="6" y="5" width="6" height="6" rx="3" fill="black"/>
                        </svg>
                    </span>
                <!--end::Svg Icon-->
                <div class="text-white fw-boldest fs-3x mb-2 mt-5">
                    {{$ishtapp_users->count()}}
                </div>
                <div class="fw-bold text-white fs-4">Пользователи</div>
                <a href="{{route('admin.report.ishtapp.users')}}" class="stretched-link"></a>
            </div>
            <!--end::Body-->
        </div>
    </div>
    <div class="col-md-4">
        <div class="card bg-primary shadow-sm card-md-stretch-50 mb-md-8">
            <!--begin::Body-->
            <div class="card-body d-flex flex-column justify-content-center">
                <!--begin::Svg Icon | path: icons/duotune/graphs/gra007.svg-->
                <span class="svg-icon svg-icon-white svg-icon-5x ms-n1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <path d="M3 2H10C10.6 2 11 2.4 11 3V10C11 10.6 10.6 11 10 11H3C2.4 11 2 10.6 2 10V3C2 2.4 2.4 2 3 2Z" fill="black"></path>
                            <path opacity="0.3" d="M14 2H21C21.6 2 22 2.4 22 3V10C22 10.6 21.6 11 21 11H14C13.4 11 13 10.6 13 10V3C13 2.4 13.4 2 14 2Z" fill="black"></path>
                            <path opacity="0.3" d="M3 13H10C10.6 13 11 13.4 11 14V21C11 21.6 10.6 22 10 22H3C2.4 22 2 21.6 2 21V14C2 13.4 2.4 13 3 13Z" fill="black"></path>
                            <path opacity="0.3" d="M14 13H21C21.6 13 22 13.4 22 14V21C22 21.6 21.6 22 21 22H14C13.4 22 13 21.6 13 21V14C13 13.4 13.4 13 14 13Z" fill="black"></path>
                        </svg>
                    </span>
                <!--end::Svg Icon-->
                <div class="text-white fw-boldest fs-3x mb-2 mt-5">
                    {{$ishtapp_companies->count()}}
                </div>
                <div class="fw-bold text-white fs-4">Компании</div>
                <a href="{{route('admin.report.ishtapp.companies')}}" class="stretched-link"></a>
            </div>
            <!--end::Body-->
        </div>
    </div>
    <div class="col-md-4">
        <div class="card bg-primary shadow-sm card-md-stretch-50 mb-md-8">
            <!--begin::Body-->
            <div class="card-body d-flex flex-column justify-content-center">
                <!--begin::Svg Icon | path: icons/duotune/graphs/gra007.svg-->
                <span class="svg-icon svg-icon-white svg-icon-5x ms-n1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <path d="M11.1359 4.48359C11.5216 3.82132 12.4784 3.82132 12.8641 4.48359L15.011 8.16962C15.1523 8.41222 15.3891 8.58425 15.6635 8.64367L19.8326 9.54646C20.5816 9.70867 20.8773 10.6186 20.3666 11.1901L17.5244 14.371C17.3374 14.5803 17.2469 14.8587 17.2752 15.138L17.7049 19.382C17.7821 20.1445 17.0081 20.7069 16.3067 20.3978L12.4032 18.6777C12.1463 18.5645 11.8537 18.5645 11.5968 18.6777L7.69326 20.3978C6.99192 20.7069 6.21789 20.1445 6.2951 19.382L6.7248 15.138C6.75308 14.8587 6.66264 14.5803 6.47558 14.371L3.63339 11.1901C3.12273 10.6186 3.41838 9.70867 4.16744 9.54646L8.3365 8.64367C8.61089 8.58425 8.84767 8.41222 8.98897 8.16962L11.1359 4.48359Z" fill="black"/>
                        </svg>
                    </span>
                <!--end::Svg Icon-->
                <div class="text-white fw-boldest fs-3x mb-2 mt-5">
                    {{$ishtapp_vacancies->count()}}
                </div>
                <div class="fw-bold text-white fs-4">Возможности</div>
                <a href="{{route('admin.report.ishtapp.opportunities')}}" class="stretched-link"></a>
            </div>
            <!--end::Body-->
        </div>
    </div>
</div>

@endsection

@section('scripts')
@endsection